-- 코드를 입력하세요
WITH MILK AS(
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'MILK'
    GROUP BY CART_ID)

SELECT CART_ID
FROM MILK AS M
WHERE CART_ID IN (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
    GROUP BY CART_ID)
ORDER BY CART_ID