WITH MAX_REVIEW AS (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
SELECT M.MEMBER_NAME
    , R.REVIEW_TEXT
    , DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS R
JOIN MEMBER_PROFILE AS M
ON R.MEMBER_ID = M.MEMBER_ID
LEFT OUTER JOIN MAX_REVIEW AS MR
ON R.MEMBER_ID = MR.MEMBER_ID
WHERE MR.MEMBER_ID IS NOT NULL
ORDER BY REVIEW_DATE, REVIEW_TEXT