-- 코드를 입력하세요
WITH MAX_INFO AS(
    SELECT CATEGORY
        , MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY)

SELECT F.CATEGORY
        , F.PRICE AS MAX_PRICE
        , F.PRODUCT_NAME
FROM FOOD_PRODUCT AS F
JOIN MAX_INFO AS M
ON F.CATEGORY = M.CATEGORY
WHERE F.PRICE = M.PRICE AND F.CATEGORY IN ('과자','국','김치','식용유')
ORDER BY MAX_PRICE DESC